#include "program.h"

// Include the cflex library header
#include "cflex.h"

// Include the header for the code generated by the cflex_build tool.
// CMake is configured to add the 'generated' directory to the include path.
#include "cflex_generated.h"

#include <stdio.h>

void run_example_program(void) {
    printf("\n--- Running Example Program ---\n");

    // Initialize the cflex library
    cflex_init();

    // Attempt to use the library to get type information.
    // In this placeholder, it will not find the type.
    const cflex_type_info_t* type_info = cflex_get_type_by_name("my_struct");
    if (type_info) {
        printf("Found type: %s, size: %u\n", type_info->name, type_info->size);
    } else {
        printf("Type 'my_struct' not found by cflex_get_type_by_name (as expected in this placeholder).\n");
    }

    // Call a function from the code generated by the pre-build step.
    printf("Calling function from generated code...\n");
    generated_function();

    printf("--- Example Program Finished ---\n");
}

int main(void) {
    run_example_program();
    return 0;
}
