#include <stdio.h>
#include <string.h>
#include <stdlib.h>

const char* generated_h_content =
    "// THIS FILE IS-GENERATED BY CFLEX_BUILD. DO NOT EDIT.\n"
    "#ifndef CFLEX_GENERATED_H\n"
    "#define CFLEX_GENERATED_H\n\n"
    "typedef enum cf_type_id_t {\n"
    "    CF_TYPE_ID_VOID, CF_TYPE_ID_BOOL, CF_TYPE_ID_CHAR, CF_TYPE_ID_I8,\n"
    "    CF_TYPE_ID_I16, CF_TYPE_ID_I32, CF_TYPE_ID_I64, CF_TYPE_ID_U8,\n"
    "    CF_TYPE_ID_U16, CF_TYPE_ID_U32, CF_TYPE_ID_U64, CF_TYPE_ID_F32,\n"
    "    CF_TYPE_ID_F64, CF_TYPE_ID_CSTR, CF_TYPE_ID_VEC2_T, CF_TYPE_ID_VEC3_T,\n"
    "    CF_TYPE_ID_PLAYER_T, CF_TYPE_ID_COLOR_T, CF_TYPE_ID_COUNT\n"
    "} cf_type_id_t;\n\n"
    "#endif // CFLEX_GENERATED_H\n";

const char* c_part1_includes =
    "// THIS FILE IS-GENERATED BY CFLEX_BUILD. DO NOT EDIT.\n"
    "#include \"cflex.h\"\n"
    "#include \"program.h\"\n"
    "#include <stddef.h>\n\n";

const char* c_part2_primitives =
    "static const cf_type_t cf_type_void = { .name = \"void\", .kind = CF_KIND_PRIMITIVE, .size = 0, .align = 0, .prim = CF_PRIM_VOID };\n"
    "static const cf_type_t cf_type_bool = { .name = \"bool\", .kind = CF_KIND_PRIMITIVE, .size = sizeof(bool), .align = _Alignof(bool), .prim = CF_PRIM_BOOL };\n"
    "static const cf_type_t cf_type_char = { .name = \"char\", .kind = CF_KIND_PRIMITIVE, .size = sizeof(char), .align = _Alignof(char), .prim = CF_PRIM_CHAR };\n"
    "static const cf_type_t cf_type_i8 = { .name = \"int8_t\", .kind = CF_KIND_PRIMITIVE, .size = sizeof(int8_t), .align = _Alignof(int8_t), .prim = CF_PRIM_I8 };\n"
    "static const cf_type_t cf_type_i16 = { .name = \"int16_t\", .kind = CF_KIND_PRIMITIVE, .size = sizeof(int16_t), .align = _Alignof(int16_t), .prim = CF_PRIM_I16 };\n"
    "static const cf_type_t cf_type_i32 = { .name = \"int32_t\", .kind = CF_KIND_PRIMITIVE, .size = sizeof(int32_t), .align = _Alignof(int32_t), .prim = CF_PRIM_I32 };\n"
    "static const cf_type_t cf_type_i64 = { .name = \"int64_t\", .kind = CF_KIND_PRIMITIVE, .size = sizeof(int64_t), .align = _Alignof(int64_t), .prim = CF_PRIM_I64 };\n"
    "static const cf_type_t cf_type_u8 = { .name = \"uint8_t\", .kind = CF_KIND_PRIMITIVE, .size = sizeof(uint8_t), .align = _Alignof(uint8_t), .prim = CF_PRIM_U8 };\n"
    "static const cf_type_t cf_type_u16 = { .name = \"uint16_t\", .kind = CF_KIND_PRIMITIVE, .size = sizeof(uint16_t), .align = _Alignof(uint16_t), .prim = CF_PRIM_U16 };\n"
    "static const cf_type_t cf_type_u32 = { .name = \"uint32_t\", .kind = CF_KIND_PRIMITIVE, .size = sizeof(uint32_t), .align = _Alignof(uint32_t), .prim = CF_PRIM_U32 };\n"
    "static const cf_type_t cf_type_u64 = { .name = \"uint64_t\", .kind = CF_KIND_PRIMITIVE, .size = sizeof(uint64_t), .align = _Alignof(uint64_t), .prim = CF_PRIM_U64 };\n"
    "static const cf_type_t cf_type_f32 = { .name = \"float\", .kind = CF_KIND_PRIMITIVE, .size = sizeof(float), .align = _Alignof(float), .prim = CF_PRIM_F32 };\n"
    "static const cf_type_t cf_type_f64 = { .name = \"double\", .kind = CF_KIND_PRIMITIVE, .size = sizeof(double), .align = _Alignof(double), .prim = CF_PRIM_F64 };\n"
    "static const cf_type_t cf_type_cstr = { .name = \"const char*\", .kind = CF_KIND_PRIMITIVE, .size = sizeof(const char*), .align = _Alignof(const char*), .prim = CF_PRIM_CSTR };\n\n";

const char* c_part3_structs =
    "static const cf_field_t cf_vec2_t_fields[] = { { \"x\", &cf_type_f32, offsetof(vec2_t, x), 0 }, { \"y\", &cf_type_f32, offsetof(vec2_t, y), 0 } };\n"
    "static const cf_type_t cf_type_vec2_t = { .name = \"vec2_t\", .kind = CF_KIND_STRUCT, .size = sizeof(vec2_t), .align = _Alignof(vec2_t), .struct_array = cf_vec2_t_fields, .struct_count = 2, .struct_parent = NULL, .struct_is_anonymous = false };\n\n"
    "static const cf_field_t cf_vec3_t_fields[] = { { \"x\", &cf_type_f32, offsetof(vec3_t, x), 0 }, { \"y\", &cf_type_f32, offsetof(vec3_t, y), 0 }, { \"z\", &cf_type_f32, offsetof(vec3_t, z), 0 } };\n"
    "static const cf_type_t cf_type_vec3_t = { .name = \"vec3_t\", .kind = CF_KIND_STRUCT, .size = sizeof(vec3_t), .align = _Alignof(vec3_t), .struct_array = cf_vec3_t_fields, .struct_count = 3, .struct_parent = NULL, .struct_is_anonymous = false };\n\n"
    "static const cf_field_t cf_player_t_fields[] = { { \"power\", &cf_type_i32, offsetof(player_t, power), 0 }, { \"health\", &cf_type_f32, offsetof(player_t, health), 0 }, { \"position\", &cf_type_vec3_t, offsetof(player_t, position), 0 } };\n"
    "static const cf_type_t cf_type_player_t = { .name = \"player_t\", .kind = CF_KIND_STRUCT, .size = sizeof(player_t), .align = _Alignof(player_t), .struct_array = cf_player_t_fields, .struct_count = 3, .struct_parent = NULL, .struct_is_anonymous = false };\n\n";

const char* c_part4_enums =
    "static const cf_enum_value_t cf_color_t_values[] = { { \"COLOR_RED\", COLOR_RED }, { \"COLOR_GREEN\", COLOR_GREEN }, { \"COLOR_BLUE\", COLOR_BLUE } };\n"
    "static const cf_type_t cf_type_color_t = { .name = \"color_t\", .kind = CF_KIND_ENUM, .size = sizeof(color_t), .align = _Alignof(color_t), .enum_array = cf_color_t_values, .enum_count = 3, .enum_is_bitflag = false };\n\n";

const char* c_part5_globals =
    "const cf_type_t* cf_type_array[] = { &cf_type_void, &cf_type_bool, &cf_type_char, &cf_type_i8, &cf_type_i16, &cf_type_i32, &cf_type_i64, &cf_type_u8, &cf_type_u16, &cf_type_u32, &cf_type_u64, &cf_type_f32, &cf_type_f64, &cf_type_cstr, &cf_type_vec2_t, &cf_type_vec3_t, &cf_type_player_t, &cf_type_color_t };\n"
    "const int32_t cf_type_count = sizeof(cf_type_array) / sizeof(cf_type_array[0]);\n";

int main(int argc, char** argv) {
    if (argc < 3) {
        fprintf(stderr, "Usage: %s <input_path> <output_path>\n", argv[0]);
        return 1;
    }
    const char* output_dir = argv[2];
    char h_path[1024];
    char c_path[1024];
    snprintf(h_path, sizeof(h_path), "%s/cflex_generated.h", output_dir);
    snprintf(c_path, sizeof(c_path), "%s/cflex_generated.c", output_dir);

    FILE* fp_h = fopen(h_path, "w");
    if (!fp_h) { return 1; }
    fprintf(fp_h, "%s", generated_h_content);
    fclose(fp_h);

    FILE* fp_c = fopen(c_path, "w");
    if (!fp_c) { return 1; }
    fprintf(fp_c, "%s", c_part1_includes);
    fprintf(fp_c, "%s", c_part2_primitives);
    fprintf(fp_c, "%s", c_part3_structs);
    fprintf(fp_c, "%s", c_part4_enums);
    fprintf(fp_c, "%s", c_part5_globals);
    fclose(fp_c);

    return 0;
}
