#include "cflex_build.h"

// This demonstrates the unity build approach.
// Platform-specific code is included directly.
#include "cflex_platform.c"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void run_cflex_build(const cflex_build_options_t* options) {
    printf("Running cflex build tool...\n");
    print_platform(); // Example function from the included platform file
    printf("Input directory: %s\n", options->input_dir);
    printf("Output directory: %s\n", options->output_dir);

    // In a real implementation, this tool would scan the input directory for C files,
    // parse them for reflection data, and then generate the output files.

    // For this placeholder, we'll just create dummy generated files.
    char generated_h_path[1024];
    char generated_c_path[1024];

    // Using platform-specific safe string functions and path separators
#ifdef _WIN32
    sprintf_s(generated_h_path, sizeof(generated_h_path), "%s\\cflex_generated.h", options->output_dir);
    sprintf_s(generated_c_path, sizeof(generated_c_path), "%s\\cflex_generated.c", options->output_dir);
#else
    snprintf(generated_h_path, sizeof(generated_h_path), "%s/cflex_generated.h", options->output_dir);
    snprintf(generated_c_path, sizeof(generated_c_path), "%s/cflex_generated.c", options->output_dir);
#endif

    FILE* h_file = fopen(generated_h_path, "w");
    if (h_file) {
        fprintf(h_file, "#ifndef CFLEX_GENERATED_H\n");
        fprintf(h_file, "#define CFLEX_GENERATED_H\n\n");
        fprintf(h_file, "#include <stdint.h>\n\n");
        fprintf(h_file, "void generated_function(void);\n\n");
        fprintf(h_file, "#endif // CFLEX_GENERATED_H\n");
        fclose(h_file);
    } else {
        fprintf(stderr, "Error: Could not open %s for writing.\n", generated_h_path);
        exit(1);
    }

    FILE* c_file = fopen(generated_c_path, "w");
    if (c_file) {
        fprintf(c_file, "#include \"cflex_generated.h\"\n");
        fprintf(c_file, "#include <stdio.h>\n\n");
        fprintf(c_file, "void generated_function(void) {\n");
        fprintf(c_file, "    printf(\"Hello from a function generated by the cflex_build tool!\\n\");\n");
        fprintf(c_file, "}\n");
        fclose(c_file);
    } else {
        fprintf(stderr, "Error: Could not open %s for writing.\n", generated_c_path);
        exit(1);
    }

    printf("Generated files created successfully in %s.\\n", options->output_dir);
}

int main(int argc, char* argv[]) {
    if (argc != 3) {
        fprintf(stderr, "Usage: %s <input_directory> <output_directory>\\n", argv[0]);
        return 1;
    }

    cflex_build_options_t options;
    options.input_dir = argv[1];
    options.output_dir = argv[2];

    run_cflex_build(&options);

    return 0;
}
