#include "cflex.h"
#include <stdio.h>

#include "internal/cflex_parser.c"

// This is a single-compilation-unit library.
// The user is expected to include this .c file into their own build,
// rather than linking against a compiled library. This is a common pattern
// for "header-only" C libraries that still need an implementation file.

void cflex_init(void) {
    printf("cflex reflection library initialized.\n");
}

const cflex_type_info_t* cflex_get_type_by_name(const char* name) {
    // In a real implementation, this would look up type information
    // from the data generated by the cflex_build tool. The generated
    // cflex_generated.c file would contain the data structures.
    printf("Searching for type: '%s'...\n", name);

    // This is just a placeholder implementation.
    if (name == NULL) {
        return NULL;
    }

    // A real implementation would search an array or hash table of types
    // that would be defined in the generated code.
    return NULL;
}
