#ifndef CFLEX_GENERATED_H
#define CFLEX_GENERATED_H

// This file is generated by the cflex build tool. It contains public symbols
// derived from user-annotated code, such as type ID enums.

// Hardcoded enum of all type IDs for direct lookups.
// The order must match the `cf_type_array` in cflex_generated.c
typedef enum cf_type_id_t {
    // Primitives
    CF_TYPE_ID_VOID,
    CF_TYPE_ID_BOOL,
    CF_TYPE_ID_CHAR,
    CF_TYPE_ID_I8,
    CF_TYPE_ID_I16,
    CF_TYPE_ID_I32,
    CF_TYPE_ID_I64,
    CF_TYPE_ID_U8,
    CF_TYPE_ID_U16,
    CF_TYPE_ID_U32,
    CF_TYPE_ID_U64,
    CF_TYPE_ID_F32,
    CF_TYPE_ID_F64,
    CF_TYPE_ID_CSTR,

    // User types
    CF_TYPE_ID_VEC2_T,
    CF_TYPE_ID_VEC3_T,
    CF_TYPE_ID_PLAYER_T,
    CF_TYPE_ID_COLOR_T,

    CF_TYPE_ID_COUNT
} cf_type_id_t;

#endif // CFLEX_GENERATED_H
