// This define is used with the dllexport/dllimport macros in the header
#define MODULE_2_EXPORTS
#include "module_2.h"

// The rest of the implementation for this module would go here.
// The reflection data is generated by the build process.
